
import os
import math
import threading
import queue
import time
import shutil
import urllib.parse
from datetime import datetime
from collections import deque
import tkinter as tk
from tkinter import ttk, messagebox

import serial
import serial.tools.list_ports

import matplotlib
matplotlib.use("TkAgg")
from matplotlib.lines import Line2D
from matplotlib.ticker import MultipleLocator
from matplotlib.backends.backend_pdf import PdfPages
from matplotlib.backends.backend_agg import FigureCanvasAgg
from matplotlib.backends.backend_tkagg import FigureCanvasTkAgg
from matplotlib.figure import Figure
import subprocess
import webbrowser
import pyautogui

BAUD_RATE = 115200          
PLOT_SECONDS = 6            
SAMPLE_INTERVAL_MS = 20    
BUFFER_SIZE = int(PLOT_SECONDS * 1000 / SAMPLE_INTERVAL_MS)
POLL_MS = 30                

RECORD_LIMIT_SECONDS = 240      
STRIP_SECONDS = 10              
STRIPS_FIRST_PAGE = 3          
STRIPS_OTHER_PAGE = 6           
REPORTS_DIR = os.path.join(os.path.expanduser("~"), "ECG_Reports")


COLOR_BG = "#0f1b2d"      
COLOR_PANEL = "#16233a"      
COLOR_ACCENT = "#00d4a0"     
COLOR_ACCENT_2 = "#ff5c7c"    
COLOR_TEXT = "#eaf1fb"
COLOR_MUTED = "#7d8ba1"


class SerialReaderThread(threading.Thread):
    def __init__(self, port, data_queue, stop_event):
        super().__init__(daemon=True)
        self.port = port
        self.data_queue = data_queue
        self.stop_event = stop_event
        self.ser = None

    def run(self):
        try:
            self.ser = serial.Serial(self.port, BAUD_RATE, timeout=1)
            time.sleep(2)
            self.ser.reset_input_buffer()
        except serial.SerialException as e:
            self.data_queue.put(("ERROR", f"UNABLE TO OPEN PORT: {e}"))
            return

        while not self.stop_event.is_set():
            try:
                raw = self.ser.readline()
                if not raw:
                    continue
                line = raw.decode("utf-8", errors="ignore").strip()

                if not line.startswith("ECG:") or ",BPM:" not in line:
                    continue 

                ecg_part, bpm_part = line.split(",BPM:")
                ecg_val = int(ecg_part.replace("ECG:", "").strip())
                bpm_val = int(bpm_part.strip())
                self.data_queue.put(("DATA", ecg_val, bpm_val))

            except (ValueError, UnicodeDecodeError):
                continue
            except serial.SerialException as e:
                self.data_queue.put(("ERROR", f"Connection dropped: {e}"))
                break

        if self.ser and self.ser.is_open:
            self.ser.close()




def _style_ecg_strip(ax):
    ax.set_facecolor("#fff0f0")
    ax.set_ylim(0, 1023)
    ax.xaxis.set_minor_locator(MultipleLocator(0.2))
    ax.xaxis.set_major_locator(MultipleLocator(1.0))
    ax.yaxis.set_minor_locator(MultipleLocator(51.15))
    ax.yaxis.set_major_locator(MultipleLocator(204.6))
    ax.grid(which="minor", color="#ffc4c4", linewidth=0.3)
    ax.grid(which="major", color="#ff8080", linewidth=0.6)
    ax.set_yticklabels([])
    for spine in ax.spines.values():
        spine.set_color("#e08080")
        spine.set_linewidth(0.6)


def generate_ecg_pdf_report(ecg_data, bpm_data, patient_info):
    os.makedirs(REPORTS_DIR, exist_ok=True)

    now = datetime.now()
    duration_sec = len(ecg_data) * SAMPLE_INTERVAL_MS / 1000
    dur_mm, dur_ss = divmod(int(duration_sec), 60)
    duration_str = f"{dur_mm:02d} min {dur_ss:02d} sec"

    if bpm_data:
        avg_bpm = round(sum(bpm_data) / len(bpm_data))
        min_bpm = min(bpm_data)
        max_bpm = max(bpm_data)
    else:
        avg_bpm = min_bpm = max_bpm = "N/A"

    safe_name = "".join(
        c for c in patient_info.get("name", "Unknown") if c.isalnum() or c in (" ", "_")
    ).strip().replace(" ", "_") or "Unknown"
    filename = f"ECG_Report_{safe_name}_{now.strftime('%Y%m%d_%H%M%S')}.pdf"
    filepath = os.path.join(REPORTS_DIR, filename)

    samples_per_strip = int(STRIP_SECONDS * 1000 / SAMPLE_INTERVAL_MS)
    total_strips = max(1, math.ceil(len(ecg_data) / samples_per_strip))

    with PdfPages(filepath) as pdf:
        strip_idx = 0
        page_num = 1

        while strip_idx < total_strips:
            fig = Figure(figsize=(8.27, 11.69))
            FigureCanvasAgg(fig)

            if page_num == 1:
                fig.text(0.5, 0.965, "ECG REPORT", fontsize=20, weight="bold",
                         ha="center", color="#2c3e50")
                fig.text(0.5, 0.940, "ROBOFUSION 1.0 — Real-Time ECG Monitoring System",
                         fontsize=10, ha="center", color="#7f8c8d")
                fig.text(0.5, 0.922, "Generated by Clever Sapiens (JSTU)",
                         fontsize=8, ha="center", style="italic", color="#95a5a6")
                fig.add_artist(Line2D([0.07, 0.93], [0.905, 0.905],
                                      transform=fig.transFigure, color="#bdc3c7", linewidth=1))

                info_y = 0.875
                gap = 0.024
                left_x, right_x = 0.09, 0.53
                rows = [
                    (f"Patient Name : {patient_info.get('name', '-')}",
                     f"Age : {patient_info.get('age', '-')}"),
                    (f"Date : {now.strftime('%d-%m-%Y')}",
                     f"Time : {now.strftime('%I:%M %p')}"),
                    (f"Duration : {duration_str}", f"Avg BPM : {avg_bpm}"),
                    (f"Min BPM : {min_bpm}", f"Max BPM : {max_bpm}"),
                ]
                for i, (left, right) in enumerate(rows):
                    fig.text(left_x, info_y - i * gap, left,
                             fontsize=10, color="#2c3e50")
                    fig.text(right_x, info_y - i * gap, right,
                             fontsize=10, color="#2c3e50")

                divider_y = info_y - 4 * gap - 0.01
                fig.add_artist(Line2D([0.07, 0.93], [divider_y, divider_y],
                                      transform=fig.transFigure, color="#bdc3c7", linewidth=1))

                top_offset = divider_y - 0.02
                n_strips = min(STRIPS_FIRST_PAGE, total_strips - strip_idx)
            else:
                top_offset = 0.95
                n_strips = min(STRIPS_OTHER_PAGE, total_strips - strip_idx)

            bottom_margin = 0.06
            strip_h = (top_offset - bottom_margin) / max(n_strips, 1)

            for i in range(n_strips):
                s_idx = strip_idx + i
                start = s_idx * samples_per_strip
                end = start + samples_per_strip
                segment = ecg_data[start:end]
                if not segment:
                    continue

                y1 = top_offset - i * strip_h
                y0 = y1 - strip_h + 0.012
                ax = fig.add_axes((0.09, y0, 0.85, strip_h - 0.018))
                _style_ecg_strip(ax)

                t = [j * SAMPLE_INTERVAL_MS /
                     1000 for j in range(len(segment))]
                ax.plot(t, segment, color="#c0392b", linewidth=0.8)
                ax.set_xlim(0, STRIP_SECONDS)
                ax.tick_params(labelsize=6, colors="#7f8c8d")
                ax.text(0.005, 0.86, f"{s_idx * STRIP_SECONDS}s\u2013{(s_idx + 1) * STRIP_SECONDS}s",
                        transform=ax.transAxes, fontsize=6, color="#7f8c8d")
                if i == n_strips - 1:
                    ax.set_xlabel("Time (seconds)",
                                  fontsize=7, color="#7f8c8d")

            fig.text(0.5, 0.02, f"Page {page_num}   \u2022   ROBOFUSION 1.0   \u2022   Clever Sapiens (JSTU)",
                     ha="center", fontsize=7, color="#95a5a6")

            pdf.savefig(fig)
            strip_idx += n_strips
            page_num += 1

    return filepath





def send_whatsapp_pdf(phone_number, pdf_path):

    """

    Copies the PDF file to the Windows clipboard via PowerShell,

    opens WhatsApp Web, and simulates Ctrl+V and Enter to send.

    """

    try:

        

        abs_path = os.path.abspath(pdf_path)

        ps_command = f"Set-Clipboard -Path '{abs_path}'"

        subprocess.run(["powershell", "-command", ps_command], check=True)



        # 2. Open default browser to WhatsApp Web chat for this number

        url = f"https://web.whatsapp.com/send?phone={phone_number}"

        webbrowser.open(url)



     

        time.sleep(20)



        pyautogui.hotkey('ctrl', 'v')

       

        

        time.sleep(3)



        

        pyautogui.press('enter')

       


        time.sleep(5)

       


        pyautogui.hotkey('ctrl', 'w')



        return True



    except Exception as e:

        print(f"Error in sending via clipboard: {e}")

        return False 






class PatientInfoDialog(tk.Toplevel):
    def __init__(self, parent):
        super().__init__(parent)
        self.title("Patient info")
        self.configure(bg=COLOR_PANEL)
        self.resizable(False, False)
        self.result = None

        self.transient(parent)
        self.grab_set()

        pad = {"padx": 14, "pady": 8}

        tk.Label(self, text="Please provide patient details before starting the recording.", bg=COLOR_PANEL,
                 fg=COLOR_ACCENT, font=("Segoe UI", 12, "bold")).grid(
            row=0, column=0, columnspan=2, padx=14, pady=(16, 12))

        tk.Label(self, text="নাম (Name):", bg=COLOR_PANEL, fg=COLOR_TEXT,
                 font=("Segoe UI", 10)).grid(row=1, column=0, sticky="e", **pad)
        self.name_entry = ttk.Entry(self, width=26, font=("Segoe UI", 10))
        self.name_entry.grid(row=1, column=1, **pad)

        tk.Label(self, text="বয়স (Age):", bg=COLOR_PANEL, fg=COLOR_TEXT,
                 font=("Segoe UI", 10)).grid(row=2, column=0, sticky="e", **pad)
        self.age_entry = ttk.Entry(self, width=26, font=("Segoe UI", 10))
        self.age_entry.grid(row=2, column=1, **pad)

        tk.Label(self, text="মোবাইল নম্বর (optional):", bg=COLOR_PANEL, fg=COLOR_TEXT,
                 font=("Segoe UI", 10)).grid(row=3, column=0, sticky="e", **pad)
        self.mobile_entry = ttk.Entry(self, width=26, font=("Segoe UI", 10))
        self.mobile_entry.grid(row=3, column=1, **pad)
        tk.Label(self, text="(যেমন: 88017XXXXXXXX, দেশের কোড সহ)", bg=COLOR_PANEL,
                 fg=COLOR_MUTED, font=("Segoe UI", 8)).grid(row=4, column=1, sticky="w", padx=14)

        self.error_var = tk.StringVar(value="")
        tk.Label(self, textvariable=self.error_var, bg=COLOR_PANEL, fg=COLOR_ACCENT_2,
                 font=("Segoe UI", 9)).grid(row=5, column=0, columnspan=2)

        btn_frame = tk.Frame(self, bg=COLOR_PANEL)
        btn_frame.grid(row=6, column=0, columnspan=2, pady=(6, 16))

        ttk.Button(btn_frame, text="▶ Start Recording",
                   command=self._on_confirm).pack(side=tk.LEFT, padx=6)
        ttk.Button(btn_frame, text="✖ বাতিল",
                   command=self._on_cancel).pack(side=tk.LEFT, padx=6)

        self.protocol("WM_DELETE_WINDOW", self._on_cancel)
        self.bind("<Return>", lambda e: self._on_confirm())
        self.name_entry.focus_set()

        self.update_idletasks()
        x = parent.winfo_x() + (parent.winfo_width() // 2) - (self.winfo_width() // 2)
        y = parent.winfo_y() + (parent.winfo_height() // 2) - (self.winfo_height() // 2)
        self.geometry(f"+{max(x, 0)}+{max(y, 0)}")

        self.wait_window(self)

    def _on_confirm(self):
        name = self.name_entry.get().strip()
        age_str = self.age_entry.get().strip()
        mobile = self.mobile_entry.get().strip()

        if not name:
            self.error_var.set("Patient Name is required")
            return
        if not age_str.isdigit() or not (0 < int(age_str) < 130):
            self.error_var.set("Patient Age (Number Only)")
            return

        if mobile and not mobile.isdigit():
            self.error_var.set("Mobile number must be digits only.")
            return

        self.result = {"name": name, "age": age_str, "mobile": mobile}
        self.destroy()

    def _on_cancel(self):
        self.result = None
        self.destroy()


class ECGMonitorApp:
    def __init__(self, root):
        self.root = root
        self.root.title(
            "ROBOFUSION 1.0  |  Real-Time ECG Monitor  —  Clever Sapiens (JSTU)")
        self.root.geometry("950x700")
        self.root.minsize(820, 620)
        self.root.protocol("WM_DELETE_WINDOW", self.on_close)

        self.data_queue = queue.Queue()
        self.stop_event = threading.Event()
        self.reader_thread = None

        self.ecg_buffer = deque([512] * BUFFER_SIZE, maxlen=BUFFER_SIZE)
        self.last_bpm = 0
        self.zero_streak = 0

        # ---- recording state ----
        self.recording = False
        self.record_ecg = []
        self.record_bpm = []
        self.record_start_time = None
        self.patient_info = None

        self._build_ui()
        self._refresh_ports()






    def _build_ui(self):
        self.root.configure(bg=COLOR_BG)

        style = ttk.Style(self.root)
        try:
            style.theme_use("clam")
        except tk.TclError:
            pass
        style.configure("TFrame", background=COLOR_BG)
        style.configure("TLabel", background=COLOR_BG,
                        foreground=COLOR_TEXT, font=("Segoe UI", 10))
        style.configure("TButton", font=("Segoe UI", 10, "bold"), padding=6,
                        background=COLOR_PANEL, foreground=COLOR_TEXT)
        style.map("TButton", background=[("active", "#22314a")])
        style.configure("Accent.TButton",
                        background=COLOR_ACCENT, foreground="#04211a")
        style.map("Accent.TButton", background=[("active", "#00b98c")])
        style.configure("Record.TButton",
                        background=COLOR_ACCENT_2, foreground="#2b0812")
        style.map("Record.TButton", background=[("active", "#e14b6c")])
        style.configure("TCombobox", fieldbackground=COLOR_PANEL, background=COLOR_PANEL,
                        foreground=COLOR_TEXT)
        style.configure("TEntry", fieldbackground="#ffffff")

        # ============================= HEADER BANNER =============================
        header = tk.Frame(self.root, bg=COLOR_PANEL)
        header.pack(side=tk.TOP, fill=tk.X)

        tk.Label(header, text="⚡ MADE FOR ROBOFUSION 1.0", bg=COLOR_PANEL, fg=COLOR_ACCENT,
                 font=("Segoe UI", 19, "bold")).pack(pady=(14, 0))
        tk.Label(header, text="Made by Clever Sapiens (JSTU)", bg=COLOR_PANEL, fg=COLOR_MUTED,
                 font=("Segoe UI", 15, "italic")).pack(pady=(2, 14))

        tk.Frame(self.root, bg=COLOR_ACCENT, height=2).pack(
            side=tk.TOP, fill=tk.X)

        # ============================= CONTROL BAR ================================
        top = tk.Frame(self.root, bg=COLOR_BG, padx=14, pady=12)
        top.pack(side=tk.TOP, fill=tk.X)

        ttk.Label(top, text=" COM Port:").pack(side=tk.LEFT, padx=(0, 6))
        self.port_combo = ttk.Combobox(top, width=15, state="readonly")
        self.port_combo.pack(side=tk.LEFT, padx=(0, 6))

        ttk.Button(top, text="⟳ Refresh", command=self._refresh_ports).pack(
            side=tk.LEFT, padx=(0, 6))

        self.connect_btn = ttk.Button(top, text="Connect", style="Accent.TButton",
                                      command=self.toggle_connection)
        self.connect_btn.pack(side=tk.LEFT, padx=(0, 14))

        self.status_label = tk.Label(top, text="● Disconnected", bg=COLOR_BG, fg="#e74c3c",
                                     font=("Segoe UI", 10, "bold"))
        self.status_label.pack(side=tk.LEFT)

        self.record_btn = ttk.Button(top, text="🔴 Record ECG (max 4 min)", style="Record.TButton",
                                     command=self.toggle_recording)
        self.record_btn.pack(side=tk.RIGHT)

        self.record_status_var = tk.StringVar(value="")
        tk.Label(top, textvariable=self.record_status_var, bg=COLOR_BG, fg=COLOR_ACCENT_2,
                 font=("Segoe UI", 10, "bold")).pack(side=tk.RIGHT, padx=12)

       
        bpm_frame = tk.Frame(self.root, bg=COLOR_PANEL, padx=16, pady=12)
        bpm_frame.pack(side=tk.TOP, fill=tk.X, padx=14, pady=(0, 12))

        tk.Label(bpm_frame, text="❤️", bg=COLOR_PANEL, font=(
            "Segoe UI", 30)).pack(side=tk.LEFT, padx=(4, 12))

        self.bpm_var = tk.StringVar(value="-- BPM")
        self.bpm_label = tk.Label(bpm_frame, textvariable=self.bpm_var, bg=COLOR_PANEL,
                                  font=("Segoe UI", 36, "bold"), fg=COLOR_ACCENT)
        self.bpm_label.pack(side=tk.LEFT, padx=10)

        self.warn_var = tk.StringVar(value="")
        tk.Label(bpm_frame, textvariable=self.warn_var, bg=COLOR_PANEL, fg="#f39c12",
                 font=("Segoe UI", 11, "bold")).pack(side=tk.LEFT, padx=20)

       
        self.fig = Figure(figsize=(8, 4), dpi=100, facecolor=COLOR_PANEL)
        self.ax = self.fig.add_subplot(111)
        self.ax.set_facecolor("#0d1420")
        self.ax.set_ylim(0, 1023)
        self.ax.set_xlim(0, BUFFER_SIZE)
        self.ax.set_title("ECG Waveform", color=COLOR_TEXT,
                          fontsize=12, fontweight="bold")
        self.ax.set_xlabel("Samples", color=COLOR_MUTED)
        self.ax.set_ylabel("ADC Value", color=COLOR_MUTED)
        self.ax.tick_params(colors=COLOR_MUTED)
        for spine in self.ax.spines.values():
            spine.set_color(COLOR_MUTED)
        self.ax.grid(True, color="#22314a", linewidth=0.5)
        self.line, = self.ax.plot(range(BUFFER_SIZE), list(self.ecg_buffer),
                                  color=COLOR_ACCENT_2, linewidth=1.3)

        self.canvas = FigureCanvasTkAgg(self.fig, master=self.root)
        self.canvas.get_tk_widget().pack(side=tk.TOP, fill=tk.BOTH,
                                          expand=True, padx=14, pady=(0, 8))
        self.canvas.draw()

        
        tk.Label(self.root, text="ROBOFUSION 1.0   •   Clever Sapiens (JSTU)",
                 bg=COLOR_BG, fg=COLOR_MUTED, font=("Segoe UI", 8)).pack(side=tk.BOTTOM, pady=6)

   
    def _refresh_ports(self):
        ports = [p.device for p in serial.tools.list_ports.comports()]
        self.port_combo["values"] = ports
        if ports:
            self.port_combo.current(0)

    def toggle_connection(self):
        if self.reader_thread and self.reader_thread.is_alive():
            self._disconnect()
        else:
            self._connect()

    def _connect(self):
        port = self.port_combo.get()
        if not port:
            self.status_label.config(text="● No port selected.", fg="#e74c3c")
            return

        self.stop_event.clear()
        self.reader_thread = SerialReaderThread(
            port, self.data_queue, self.stop_event)
        self.reader_thread.start()

        self.connect_btn.config(text="Disconnect")
        self.status_label.config(
            text=f"● Connecting to {port}...", fg="#f39c12")

    def _disconnect(self):
        if self.recording:
            self._stop_recording(auto=True)
        self.stop_event.set()
        if self.reader_thread:
            self.reader_thread.join(timeout=2)
        self.connect_btn.config(text="Connect")
        self.status_label.config(text="● Disconnected", fg="#e74c3c")

   
    def toggle_recording(self):
        if self.recording:
            self._stop_recording(auto=False)
            return

        if not (self.reader_thread and self.reader_thread.is_alive()):
            messagebox.showwarning(
                "Warning", "Please connect the device before starting the recording.")
            return

        dialog = PatientInfoDialog(self.root)
        if not dialog.result:
            return

        self.patient_info = dialog.result
        self.record_ecg = []
        self.record_bpm = []
        self.record_start_time = time.time()
        self.recording = True
        self.record_btn.config(text="⏹ Stop & Save")

    def _stop_recording(self, auto):
        self.recording = False
        self.record_btn.config(text="🔴 Record ECG (max 4 min)")

        ecg_data = list(self.record_ecg)
        bpm_data = list(self.record_bpm)
        patient_info = dict(self.patient_info) if self.patient_info else {
            "name": "Unknown", "age": "-", "mobile": ""}

        if len(ecg_data) < 10:
            self.record_status_var.set("")
            if not auto:
                messagebox.showwarning(
                    "Warning", "Not enough ECG data recorded, could not generate PDF.")
            return

        self.record_status_var.set("Creating PDF..... ")
        threading.Thread(target=self._generate_and_send,
                         args=(ecg_data, bpm_data, patient_info), daemon=True).start()

    def _generate_and_send(self, ecg_data, bpm_data, patient_info):
        try:
            pdf_path = generate_ecg_pdf_report(ecg_data, bpm_data, patient_info)
            self.root.after(0, lambda: self._on_pdf_done(pdf_path, None))

            mobile = patient_info.get("mobile", "").strip()
            if mobile:
                self.root.after(0, lambda: self.record_status_var.set("Sending via WhatsApp..."))
                send_thread = threading.Thread(target=self._send_whatsapp_worker,
                                               args=(mobile, pdf_path), daemon=True)
                send_thread.start()
        except Exception as e:
            self.root.after(0, lambda: self._on_pdf_done(None, e))

    def _send_whatsapp_worker(self, mobile, pdf_path):
        try:
            success = send_whatsapp_pdf(mobile, pdf_path)
            if success:
                self.root.after(0, lambda: self.record_status_var.set("WhatsApp sent ✓"))
            else:
                self.root.after(0, lambda: self.record_status_var.set("WhatsApp send failed"))
        except Exception as e:
            error_msg = f"WhatsApp send error: {e}"
            self.root.after(0, lambda: messagebox.showerror("WhatsApp Error", error_msg))
            self.root.after(0, lambda: self.record_status_var.set("WhatsApp send failed"))

    def _on_pdf_done(self, path, error):
        self.record_status_var.set("")
        if error:
            messagebox.showerror("ERROR", f"Error in generating PDF:\n{error}")
        else:
            messagebox.showinfo(
                "Save complete", f"ECG report has been saved:\n{path}")

    
    def poll_queue(self):
        got_data = False
        try:
            while True:
                item = self.data_queue.get_nowait()
                if item[0] == "ERROR":
                    self.status_label.config(text=f"● {item[1]}", fg="#e74c3c")
                    self.connect_btn.config(text="Connect")
                    if self.recording:
                        self._stop_recording(auto=True)
                elif item[0] == "DATA":
                    _, ecg_val, bpm_val = item
                    self.ecg_buffer.append(ecg_val)
                    if bpm_val > 0:
                        self.last_bpm = bpm_val

                    if ecg_val == 0 and bpm_val == 0:
                        self.zero_streak += 1
                    else:
                        self.zero_streak = 0

                    if self.recording:
                        self.record_ecg.append(ecg_val)
                        if bpm_val > 0:
                            self.record_bpm.append(bpm_val)

                    got_data = True
        except queue.Empty:
            pass

        if got_data:
            self.status_label.config(text="● Connected", fg=COLOR_ACCENT)
            self.line.set_ydata(list(self.ecg_buffer))
            self.canvas.draw_idle()

            self.bpm_var.set(
                f"{self.last_bpm} BPM" if self.last_bpm else "-- BPM")
            if self.last_bpm:
                if 60 <= self.last_bpm <= 100:
                    self.bpm_label.config(fg=COLOR_ACCENT)
                else:
                    self.bpm_label.config(fg="#e67e22")

            if self.zero_streak > 15:
                self.warn_var.set("⚠ Leads Off Detected — CHECK ELECTRODE")
            else:
                self.warn_var.set("")

        # recording timer
        if self.recording and self.record_start_time is not None:
            elapsed = time.time() - self.record_start_time
            mm, ss = divmod(int(elapsed), 60)
            self.record_status_var.set(
                f"Recording.... {mm:02d}:{ss:02d} / 04:00")
            if elapsed >= RECORD_LIMIT_SECONDS:
                self._stop_recording(auto=True)

        self.root.after(POLL_MS, self.poll_queue)

    def on_close(self):
        self.stop_event.set()
        if self.reader_thread:
            self.reader_thread.join(timeout=2)
        self.root.destroy()


if __name__ == "__main__":
    root = tk.Tk()
    app = ECGMonitorApp(root)
    app.poll_queue()
    root.mainloop()